@startuml MaestroArchitecture
!include Admin/admin_parts.puml
!include FAISS/faiss_parts.puml
!include FindReply/find_reply_parts.puml
'skinparam linetype polyline

skinparam rectangle<<UNCHANGED>>{
	'BorderColor Gray
    BackgroundColor GainsBoro
}

skinparam rectangle<<INTEREST>>{
    BorderColor DarkOrange
    BackgroundColor AliceBlue
}

skinparam rectangle<<OUTOFSCOPE>>{
    'BorderColor DeepSkyBlue
    BackgroundColor AliceBlue
}

' actor Dashboard
' actor WebApp
' actor WebChat

' rectangle GUIs {
'     rectangle Backend
'     rectangle Proxy
'     rectangle Mercure
'     Backend <-d-> Proxy: REST
'     Backend -> Mercure
' }

' Dashboard --> Backend: REST
' WebApp --> Backend: REST
' WebChat --> Backend: REST
' Proxy -u-> WebApp: Websockets
' Mercure -u-> WebChat: sse

rectangle Conversations <<OUTOFSCOPE>>{
   frame "Dedicated\nRasa" as Rasa <<CONTAINER>> {
       'control " " as RasaCtrl
   }
}

cloud Administrator {
    actor "Dashboard" as admingui
    rectangle "Backend\nProxy" as adminbackend
    admingui -> adminbackend<<INTRA>>
}
cloud Users {
    rectangle "Backend\nProxy || Mercure" as userbackend
    actor "Web\nApp/Chat" as usergui
    usergui -l-> userbackend<<INTRA>>
}



rectangle "Dedicated\nMaestro" as Maestro <<INTEREST>>{
    frame Admin <<CONTAINER>> {
        'atabase "Data" as AdminData
    }

    frame FindReply <<CONTAINER>> {
        'control " " as FindReplyControl
    }

    frame Faiss <<CONTAINER>> {
        'database "Search\nEngine" as SearchEngine
    }
}



rectangle Data <<UNCHANGED>>{
    frame Gogs <<CONTAINER>>  {
        database "Git Repo" as GitREpo
    }
}

rectangle "General Purpose\nNeural Networks" <<OUTOFSCOPE>>{
    frame "Sentence\nmatching" as sentencematching <<CONTAINER>>
    frame "Sentence\nencoder" as bertencoder <<CONTAINER>>
    
}

FindReply o-0)-> bertencoder: get vectors
FindReply o-0)-> sentencematching: get match
Admin o-0)-> bertencoder: get vectors

adminbackend o-0)-> Admin: <b> Drive</b>

FindReply --> Admin <<INTRA>>:  Get Infos
FindReply --> Faiss <<INTRA>>: Search
Admin -> Faiss <<INTRA>>: Update

Rasa o-0)-> FindReply: <b> Ask</b>
adminbackend --> GitREpo: <b> Push</b>
Admin --> GitREpo:<b> Pull</b>

userbackend -l-> Rasa: <b> Talk to</b>



@enduml

@startuml Rasa
!include Admin/admin_parts.puml
skinparam rectangle<<OUTOFSCOPE>>{
    'BorderColor DeepSkyBlue
    BackgroundColor AliceBlue
}
rectangle Conversations <<OUTOFSCOPE>>{
   frame "Dedicated\nRasa" as Rasa <<CONTAINER>> {
       'control " " as RasaCtrl
   }
}
@enduml

@startuml IAs
!include Admin/admin_parts.puml
skinparam rectangle<<OUTOFSCOPE>>{
    'BorderColor DeepSkyBlue
    BackgroundColor AliceBlue
}
rectangle "General Purpose\nNeural Networks" <<OUTOFSCOPE>>{
    frame "Sentence\nmatching" as sentencematching <<CONTAINER>>
    frame "Sentence\nencoder" as bertencoder <<CONTAINER>>
    
}
@enduml