@startuml CommandsMaster
!includeurl https://raw.githubusercontent.com/momenttech/plantuml/master/globals/commons.puml
'!include ./globals/commons.puml
'skinparam linetype ortho
'skinparam linetype polyline
'left to right direction
'top to bottom direction
skinparam nodesep 30
skinparam ranksep 20
scale 1
' rectangle "Master Inputs" as MasterQuestions {
'     actor "Ask: who is master" as MasterAsk
'     actor "Reply: I'm master" as MasterReply
'     MasterAsk .[hidden]. MasterReply
' }

skinparam rectangle<<QUEUES>>{
    FontColor $PURPLE
    FontStyle none
	BorderColor $PURPLE
	BackgroundColor #White|LightSteelBlue
}
skinparam rectangle<<EXCHANGE>>{
    FontColor $PURPLE
    FontStyle none
	BorderColor $PURPLE
	BackgroundColor #White|LightSeaGreen
}


rectangle "RabbitMQ Broker" as RmqBroker {
    
    rectangle "Master's Inputs Queue" <<QUEUES>> as RmqQueuesIn {
        card Card_TbottAdmin [
            tbott_admin_master
            ___
            ---
            ---
            ---
            ---
        ]
    }
    rectangle "Topic Exchanges" <<EXCHANGE>> as TopicEx {
        control "tbott_admin_master" as ExchTbott

    }
    rectangle "Admins' Queues" <<QUEUES>> as RmqQueuesOut {
        card Card_A0P0T0Q1 [
            COUNCIL_<b>Q</b>_A0_P0_prod_uid1
            ___
            ---
            ---
            ---
            ---
        ]
        card Card_A0P0T0A1 [
            COUNCIL_<b>A</b>_A0_P0_prod_uid1
            ___
            ---
            ---
            ---
            ---
            ---
        ]
        card Card_A0P0T0A2 [
            COUNCIL_<b>Q</b>_A0_P0_prod_uid2
            ___
            ---
            ---
            ---
            ---
            ---
        ]
        card Card_A0P0T0Q2 [
            COUNCIL_<b>A</b>_A0_P0_prod_uid2
            ___
            ---
            ---
            ---
            ---
            ---
        ]

    }

}

'MasterAsk -l-> Card_TbottAdmin
'MasterReply -l-> Card_TbottAdmin
Card_TbottAdmin -d-> ExchTbott

ExchTbott --> Card_A0P0T0A1: "routing:\nCOUNCIL.<b>A</b>.A0.P0.prod.#"
ExchTbott --> Card_A0P0T0Q1: "routing:\nCOUNCIL.<b>Q</b>.A0.P0.prod.#"
ExchTbott --> Card_A0P0T0A2: "routing:\nCOUNCIL.<b>A</b>.A0.P0.prod.#"
ExchTbott --> Card_A0P0T0Q2: "routing:\nCOUNCIL.<b>Q</b>.A0.P0.prod.#"

frame "Admin" as FrameA0P0T1 {
    component CompA0P0T1 [
        Domain: <b>A0</b> (cfg)
        Project: <b>P0</b> (cfg)
        Target: <b>prod</b> (cfg)
        Uuid : uid1 (auto.)
    ]
}

frame "Admin" as FrameA0P0T2 {
    component CompA0P0T2 [
        Domain: <b>A0</b> (cfg)
        Project: <b>P0</b> (cfg)
        Target: <b>prod</b> (cfg)
        Uuid : uid2 (auto.)
    ]
}

FrameA0P0T1 -> Card_TbottAdmin: "Who is\nmaster\nCOUNCIL.<b>Q</b>.A0.P0.prod.#"
FrameA0P0T2 -> Card_TbottAdmin: "I'm\nmaster\nCOUNCIL.<b>A</b>.A0.P0.prod.#"
'Com -u-> MasterQuestions

Card_A0P0T0A1 --> CompA0P0T1: topic\nCOUNCIL.<b>A</b>.A0.P0.prod.uid1
Card_A0P0T0Q1 --> CompA0P0T1: topic\nCOUNCIL.<b>Q</b>.A0.P0.prod.uid1
Card_A0P0T0A2 --> CompA0P0T2: topic\nCOUNCIL.<b>A</b>.A0.P0.prod.uid2
Card_A0P0T0Q2 --> CompA0P0T2: topic\nCOUNCIL.<b>Q</b>.A0.P0.prod.uid2


@enduml