@startuml FAISS_Full
!include faiss_parts.puml

interface "<b>Start Here</b>" as FAISSØMQ
$Container("FaissModule") {
    '"all", "variables", "ports", "volumes", "extra"
    $make_docker_config("all") 
    'top to bottom direction
    '"all", "EntryPoint", "ManageIndex", "FaissIndex"
    $make_content("all")
}
@enduml

@startuml FAISS_Config
!include faiss_parts.puml
$make_docker_config("all") 
@enduml

@startuml FAISS_EntryPoint
!include faiss_parts.puml
$make_content("EntryPoint")
@enduml

@startuml FAISS_ManageIndex
!include faiss_parts.puml
$make_content("ManageIndex")
@enduml

@startuml FAISS_FaissIndex
!include faiss_parts.puml
$make_content("FaissIndex")
@enduml